### ISSUE TITLE
Align the test search location with the configuration based build location

### ISSUE THREAD

**Issue by m17kea** [derivitec-archive/cmake-test-explorer#2]
In our solution we use the Microsoft CMake Tools extension. This has the following setting for the location of the build output which can parse both the workspace folder and buildType (Debug, Release, etc):
```
"cmake.buildDirectory": "${workspaceFolder}/src/build/${buildType}"
```
In the CMake Test Explorer there is the following setting:
```
"cmakeExplorer.buildDir": "src/build/Debug",
```

This does not seem to parse the same variables and is treated differently. Could we add the option to use the CMake Tools setting directly or at least parse in the same way.

**Comment by andrewbridge** [comment]
Fixed by https://github.com/Derivitec/cmake-test-explorer/commit/88fba05a58b892140f4527169e7304596436258b
